eureka:
  client:
    register-with-eureka: false


server:
  port: 8222


spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: coffee-consumer
          uri: http://localhost:9001
          predicates:
            - Path=/**
        - id: coffee-maker
          uri: http://localhost:9000
          predicates:
            - Path=/**